const cards = [
    {
        id: 1,
        rank: '6',
        iconNumber: 6,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon',
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 2,
        rank: '7',
        iconNumber: 7,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon',
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: 'ab-7',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 3,
        rank: '8',
        iconNumber: 8,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: 'ab-7',
        absoluteClass2: 'ab-8',
        color: 'black'
    },
    {
        id: 4,
        rank: '9',
        iconNumber: 9,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-9',
        rotateClass: 4,
        absoluteClass1: 'ab-9',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 5,
        rank: '10',
        iconNumber: 10,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-9',
        rotateClass: 4,
        absoluteClass1: 'ab-10-top',
        absoluteClass2: 'ab-10-bottom',
        color: 'black'
    },
    {
        id: 6,
        rank: 'J',
        iconNumber: 1,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 7,
        rank: 'Q',
        iconNumber: 1,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 8,
        rank: 'K',
        iconNumber: 1,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 9,
        rank: 'A',
        iconNumber: 1,
        suit: 'spade',
        url: './assets/img/spade.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 10,
        rank: '6',
        iconNumber: 6,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon',
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 11,
        rank: '7',
        iconNumber: 7,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon',
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: 'ab-7',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 12,
        rank: '8',
        iconNumber: 8,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: 'ab-7',
        absoluteClass2: 'ab-8',
        color: 'black'
    },
    {
        id: 13,
        rank: '9',
        iconNumber: 9,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-9',
        rotateClass: 4,
        absoluteClass1: 'ab-9',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 14,
        rank: '10',
        iconNumber: 10,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-9',
        rotateClass: 4,
        absoluteClass1: 'ab-10-top',
        absoluteClass2: 'ab-10-bottom',
        color: 'black'
    },
    {
        id: 15,
        rank: 'J',
        iconNumber: 1,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 16,
        rank: 'Q',
        iconNumber: 1,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 17,
        rank: 'K',
        iconNumber: 1,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 18,
        rank: 'A',
        iconNumber: 1,
        suit: 'club',
        url: './assets/img/club.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'black'
    },
    {
        id: 19,
        rank: '6',
        iconNumber: 6,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon',
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 20,
        rank: '7',
        iconNumber: 7,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon',
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: 'ab-7',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 21,
        rank: '8',
        iconNumber: 8,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: 'ab-7',
        absoluteClass2: 'ab-8',
        color: 'red'
    },
    {
        id: 22,
        rank: '9',
        iconNumber: 9,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-9',
        rotateClass: 4,
        absoluteClass1: 'ab-9',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 23,
        rank: '10',
        iconNumber: 10,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-9',
        rotateClass: 4,
        absoluteClass1: 'ab-10-top',
        absoluteClass2: 'ab-10-bottom',
        color: 'red'
    },
    {
        id: 24,
        rank: 'J',
        iconNumber: 1,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 25,
        rank: 'Q',
        iconNumber: 1,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 26,
        rank: 'K',
        iconNumber: 1,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 27,
        rank: 'A',
        iconNumber: 1,
        suit: 'heart',
        url: './assets/img/heart.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 28,
        rank: '6',
        iconNumber: 6,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon',
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 29,
        rank: '7',
        iconNumber: 7,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon',
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: 'ab-7',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 30,
        rank: '8',
        iconNumber: 8,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-6',
        rotateClass: 2,
        absoluteClass1: 'ab-7',
        absoluteClass2: 'ab-8',
        color: 'red'
    },
    {
        id: 31,
        rank: '9',
        iconNumber: 9,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-9',
        rotateClass: 4,
        absoluteClass1: 'ab-9',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 32,
        rank: '10',
        iconNumber: 10,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-9',
        rotateClass: 4,
        absoluteClass1: 'ab-10-top',
        absoluteClass2: 'ab-10-bottom',
        color: 'red'
    },
    {
        id: 33,
        rank: 'J',
        iconNumber: 1,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 34,
        rank: 'Q',
        iconNumber: 1,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 35,
        rank: 'K',
        iconNumber: 1,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
    {
        id: 36,
        rank: 'A',
        iconNumber: 1,
        suit: 'diamond',
        url: './assets/img/diamond.svg',
        altText: 'spade-icon', 
        suitClass: 'suit-j',
        rotateClass: 0,
        absoluteClass1: '',
        absoluteClass2: '',
        color: 'red'
    },
]